### ISSUE TITLE
Causes error when debugging in typescript project

### ISSUE THREAD

**Issue by bmewburn** [aspnet/Razor.VSCode#275] opened 2019-01-03 20:42 UTC
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce
1. Install ms-vscode.csharp
2. Go to a Typescript project and start debugging with F5

#### Description of the problem:
If I have ms-vscode.csharp installed and try to start debugging a Typescript project I get errors shown in the output relating to Razor.VSCode and the Typescript debugging fails to run correctly. I have to disable ms-vscode.csharp to use the Typescript debugger. The workspace contains only js, ts and php files.

Expected behavior:
Start Typescript debugging

Actual behavior:
Razor.VSCode output panel is opened, displaying error below. Typescript debugging fails to start.
![screenshot from 2019-01-04 07-25-54](https://user-images.githubusercontent.com/5885195/50660276-563fc480-0ff3-11e9-8123-25231da16885.png)

**Comment by NTaylorMullen** [comment] 2019-01-03 22:52
Duplicate of https://github.com/aspnet/Razor.VSCode/issues/222 and https://github.com/aspnet/Razor.VSCode/issues/223.

You can work around this by setting `razor.disabled` to `true`

**Closed by NTaylorMullen** 2019-01-03 22:52 UTC
