### ISSUE TITLE
😂I don't know how to describe it 😂,  but I hope you fix it earlier, thanks a lot

### ISSUE THREAD

**Issue by larryw3i** [aspnet/Razor.VSCode#383] opened 2019-07-27 18:25 UTC
Everything's in the **pictures** >_
![display bug](https://raw.githubusercontent.com/larryw3i/tomato/master/Screenshot%20from%202019-07-28%2001-44-26_.webp)    
![display bug](https://raw.githubusercontent.com/larryw3i/tomato/master/Screenshot%20from%202019-07-28%2001-56-02_.webp)  
![display bug](https://raw.githubusercontent.com/larryw3i/tomato/master/Screenshot%20from%202019-07-28%2002-21-02.webp)

**Comment by NTaylorMullen** [comment] 2019-07-29 16:54
@larryw3i I really appreciate the bug report. There's are very specific examples that will help us to resolve this quickly in the future!

For now I'm gonna close this as a duplicate of https://github.com/aspnet/Razor.VSCode/issues/75 in order to track this work there.

**Closed by NTaylorMullen** 2019-07-29 16:54 UTC
Labels: duplicate
