### ISSUE TITLE
Razor comment TextMate display incorrectly when "@if" is used

### ISSUE THREAD

**Issue by larryw3i** [aspnet/Razor.VSCode#406] opened 2019-09-18 13:19 UTC
<img src='https://raw.githubusercontent.com/larryw3i/tomato/master/Screenshot%20from%202019-09-18%2021-07-48.webp'/>

**Comment by NTaylorMullen** [comment] 2019-09-18 17:33
Haha, look at that. Nice catch 😄. Going to close this as a duplicate of https://github.com/aspnet/Razor.VSCode/issues/75. Me linking to that issue will ensure we cover this scenario when we fix Razor's textmate grammar.

**Closed by NTaylorMullen** 2019-09-18 17:33 UTC
Labels: duplicate
