### ISSUE TITLE
 TextMate display  incorrectly when multi-brackets are used

### ISSUE THREAD

**Issue by larryw3i** [aspnet/Razor.VSCode#390] opened 2019-08-12 17:14 UTC
TextMate display  incorrectly when multi-brackets are used >_      
<img src='https://raw.githubusercontent.com/larryw3i/tomato/master/Screenshot%20from%202019-08-13%2000-54-34.webp'/>     
(pay attention to the tag color)

**Comment by NTaylorMullen** [comment] 2019-08-12 17:16
Ooo interesting catch. Thanks @larryw3i for the detail! 

Going to close this as a duplicate of https://github.com/aspnet/Razor.VSCode/issues/75 for now. We're tracking the work over there.

**Closed by NTaylorMullen** 2019-08-12 17:16 UTC

**Comment by larryw3i** [comment] 2019-08-12 17:34
> Ooo interesting catch. Thanks @larryw3i for the detail!
> 
> Going to close this as a duplicate of #75 for now. We're tracking the work over there.

Thank you @NTaylorMullen
