### ISSUE TITLE
Minimal code completion for Razor files in WSL

### ISSUE THREAD

**Issue by Drakota** [aspnet/Razor.VSCode#404] opened 2019-09-11 16:31 UTC
## Issue Description ##
I'm currently trying to make the C# extension give accurate auto completion for a .cshtml file, but for some reasons, I have minimal auto completion for the default MVC template of .NET Core

## Steps to Reproduce ##
1. Install WSL 2.0
2. Install .NET Core from this [link](https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-2.2.109)
3. Setup the basic MVC example from this [link](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?view=aspnetcore-2.2&tabs=visual-studio-code)
4. Try to get some auto completion

## Expected Behavior ##
Having auto completions like this
![image](https://devblogs.microsoft.com/wp-content/uploads/sites/16/2019/02/razor-tooling-html-completions.gif)
![image](https://devblogs.microsoft.com/wp-content/uploads/sites/16/2019/02/razor-tooling-directive-completions.gif)

## Actual Behavior ##
The only completions I have and absolutely no HTML completion whatsoever.
![Capture2](https://user-images.githubusercontent.com/22665836/64715633-dc6baf00-d48e-11e9-8635-61340046195d.PNG)
![Capture3](https://user-images.githubusercontent.com/22665836/64715639-dd9cdc00-d48e-11e9-9e40-b40d3b58f662.PNG)

## Environment information ##

**VSCode version**: 1.39.0-insider
**C# Extension**: 1.21.2

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   2.2.109
 Commit:    586f23c400

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.109/

Host (useful for support):
  Version: 2.2.7
  Commit:  b1e29ae826

.NET Core SDKs installed:
  2.2.109 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.25.1|
|csharp|ms-vscode|1.21.2|
|dart-code|Dart-Code|3.4.1|
|easy-cpp-projects|ACharLuk|1.7.7|
|flutter|Dart-Code|3.4.1|
|gitlens|eamodio|9.9.3|
|laravel-blade|onecentlin|1.20.0|
|path-intellisense|christian-kohler|1.4.2|
|prisma|Prisma|0.0.15|
|project-manager|alefragnani|10.7.0|
|python|ms-python|2019.9.34911|
|rust|rust-lang|0.6.3|
|vscode-graphql|Prisma|0.2.1|
|vscode-intelephense-client|bmewburn|1.2.3|
|vscode-jest|Orta|3.0.2|
|vscode-typescript-tslint-plugin|ms-vscode|1.2.2|
|vscode-yaml|redhat|0.5.2|
|vscodeintellicode|VisualStudioExptTeam|1.1.9|;

</details>

## Razor Server Logs ##
[pastebin](https://pastebin.com/bsV2ADJY)

**Comment by NTaylorMullen** [comment] 2019-09-17 17:16
@Drakota thanks for the detailed report. Are you using remote development to dev in WSL or are you remoting? Also, would you mind sharing the Omnisharp Logs as well?

**Comment by Drakota** [comment] 2019-09-18 00:27
Hi! Thanks for taking the time to review this issue.
I'm not quite sure about what you're asking, as I understand it is am I using the remote development extension to open my project inside WSL. 
![image](https://user-images.githubusercontent.com/22665836/65088916-19510d80-d989-11e9-884e-3cab6604c44c.png)
[Here's the Omnisharp logs](https://pastebin.com/ZPHt3kqg)

**Comment by NTaylorMullen** [comment] 2019-09-18 17:31
> I'm not quite sure about what you're asking, as I understand it is am I using the remote development extension to open my project inside WSL. I also have the C# extension installed in WSL.

Ahhh I see. We've yet to implement remote development for Razor in VSCode sadly. For now i'm going to close this issue as a duplicate of [this](https://github.com/aspnet/Razor.VSCode/issues/393) (implement remote development).

**Closed by NTaylorMullen** 2019-09-18 17:31 UTC
